### ISSUE TITLE
Display short path for location

### ISSUE THREAD

**Issue by KillianKemps** [vitiral/rst#1]
Currently when doing `rsk ls` we get something like this:

```
|--|     0%     0% | TST-learn-partof  |  | /home/username/some/long/path/tutorial.rsk 
```
It would be nicer to have just `tutorial.rsk` instead of the whole `/home/username/some/long/path/tutorial.rsk ` path. In fact, having the long path is even useless because only files beneath or at the same level of the `.rsk` folder are interpreted.
Having the same behaviour as git for displaying files would be great.

**Comment by vitiral** [comment]
agreed, this will be done along with the ui tests which are comming in the next minor release.

The behavior I was going to do was display the path from the `{repo}` folder (same folder `.rsk` folder is in).

I think the correct route here is to have two behaviors:
 - if `-l` is specified (long form), display the `git path`
 - otherwise, display only the file name.

Does that make sense? Or should the `git path` always be displayed? I am torn.

**Comment by KillianKemps** [comment]
I think always displaying the `git path` is the best option because

1. We are already used to this behaviour with git
2. The user may have multiple files with the same name. So having this `git path` avoids conflicts and user mistakes. For example, I see that for `rsk` itself you have several `settings.rsk` files: at `reqs/settings.rsk` and at `reqs/core/settings.rsk`
3. If the user follows the best practices of your tutorial, the path from `{repo}` should not be very long. At least, `git path` will always be shorter than the whole path so it's always better.

Just to be sure we understand each other, what you mean by `git path` is 
```
reqs/purpose.rsk 
```
where `reqs` is child of `{repo}`
And we agree that this is much more clearer than
```
/home/username/some/long/path/{repo}/reqs/purpose.rsk 
```

**Comment by vitiral** [comment]
I think you are right: always display the git path.

`git path` means a little more -- it is the relative path *from the cwd`

so if I am in the `reqs

**Comment by KillianKemps** [comment]
Yes you are right for the relative path. I think we are okay for how to implement file path!

**Comment by vitiral** [comment]
Sounds good. Something I realized is that the repo is irrelevant -  all git does is relative path. Should be fairly simple

**Comment by KillianKemps** [comment]
Oh you're right, it's simply a relative path. Nice
