### ISSUE TITLE
`rst -h` text is outdated

### ISSUE THREAD

**Issue by IslandUsurper** [vitiral/rst#3]
Calling `rst -h` as described in the README gives the following output:

> rst 0.0.1
> https://github.com/vitiral/rst
> the requirements tracking tool made for developers. Call `rst init -t` for a tutorial

Cargo installed rst v0.1.4, so the reported version number is wrong (this should be a separate issue, perhaps, because `rst -V` does the same thing), and "-t" is an unrecognized flag for `init`, presumably superseded by the `tutorial` command.

**Comment by vitiral** [comment]
thanks for the bug report! Fix is in mainline, will be in next patch release.
