### ISSUE TITLE
Add headers to `rst ls` output

### ISSUE THREAD

**Issue by IslandUsurper** [vitiral/rst#5]
It's not immediately obvious what the different columns mean in the short format of `rst ls`. I eventually figured out that "D" means "Done" and "T" means "Tested", but a key would be nice. `dpkg-query -l` has a good example of what I mean.

Especially in the first parts of the tutorial when you only have artifacts and no code, it's really hard to tell what you're looking at.

**Comment by vitiral** [comment]
I totally agree. This will be in the next batch of `ls` changes.
