### ISSUE TITLE
i should have been faster

### ISSUE THREAD

**Issue by flying-sheep** [vitiral/rst#6]
i intended to finish my reStructuredText library one day.

i’m really sad i can’t use this name anymore :cry:

**Comment by vitiral** [comment]
oh that's not good! I think the community and simple names come first. 

So, this is a binary library -- I don't really need the name in cargo to be super nice. I would be willing to give you ownership of the Cargo name if you help me come up with a different cargo name (and answer a few questions because I'm fairly new)

First, the question. Right now this is a `bin`. If later I wanted to provide an API for people to use, is it possible it could be both a `lib` and a `bin` in the future?

If so, I could rename it something like `rst_app` in cargo. `rst_cmd` would also be fine, although it's a bit more than a cmd (will have a webui in the future).

**Comment by vitiral** [comment]
also we have to transfer soon, before this library gets used too much

**Comment by vitiral** [comment]
what is the conventional name for something that is intended to be used as a cmd/application? `rst_bin` maybe?

**Comment by porglezomp** [comment]
A crate can contain one `lib` target and multiple `bin` targets, if I remember correctly, so you're good on that front.

**Comment by vitiral** [comment]
Ok, thanks @porglezomp.

@flying-sheep I would be willing to give up the name and re-name this repo to `rst_app` in cargo. It looks like I need to do `cargo owner --add FLYINGSHEEP` -- let me know which username I should transfer ownership to

**Comment by flying-sheep** [comment]
hi, that’s really nice! however, if you plan to provide a library as well, i’ll simply take the name “rest” (because you can abbreviate reStructuredText as rST and reST alike)

@ your question: i had the same one about bin and lib, and found the answer by @shepmaster [here](http://stackoverflow.com/a/26953326/247482):

> ```console
> $ tree
> .
> ├── Cargo.toml
> └── src
>     ├── bin
>     │   └── mybin.rs
>     └── lib.rs
> 
> $ cat Cargo.toml
> [package]
> name = "mylib"
> version = "0.0.1"
> authors = ["me <me@gmail.com>"]
> ```
> 
> Additionally, you can just create a src/main.rs that will be used as the defacto executable. Unfortunately, this conflicts with the cargo doc command:
> 
> > Cannot document a package where a library and a binary have the same name. Consider renaming one or marking the target as doc = false

**Comment by vitiral** [comment]
plz don't take "rest", that will conflict with the REST API (plus that is a really great name).

If `rst_app` can be both a lib and a bin then there isn't any problem (honestly, `app` is more descriptive as that will always be it's primary purpose -- the point of exporting a lib API would just be for plugins)

**Comment by vitiral** [comment]
plus, I can always just create a `rst_lib` if I really need to. I might just reserve that ahead of time if it makes things easier.

What username should I transfer ownership to?

**Comment by flying-sheep** [comment]
oh, didn’t think about REST.

i should be flying-sheep there, too, right? it only allows logging in via GitHub after all

**Comment by vitiral** [comment]
sounds good, I will do this for the next minor release. Stay tuned to this issue.

**Comment by flying-sheep** [comment]
i am!

**Comment by vitiral** [comment]
alright, I have added flying-sheep as an owner and all versions have been yanked:

https://crates.io/crates/rst/versions

Let me know if there is anything else I can do

**Comment by vitiral** [comment]
Note to those coming to this ticket, this library has been renamed to **rst_app** in **cargo only** (you still call it with `rst`)

https://crates.io/crates/rst_app

**Comment by flying-sheep** [comment]
that was a really nice thing of you to do. i’ll try to honor it adequately by finally getting my reStructuredText project going!

**Comment by vitiral** [comment]
awesome, no problem. I'm not much of a user of ReStructuredText, but I can imagine my frustration with having to import anything but the obvious `rst`.

Can you link to the source code of your library here?

**Comment by flying-sheep** [comment]
here: https://github.com/flying-sheep/rust-rst

as previously warned, it’s not far. i have the data structures almost nailed down, but no parser exists yet.

emitting HTML and XML should be easy though

**Comment by vitiral** [comment]
cool, thanks for working on the core rust tooling -- it is very needed!

**Comment by fbender** [comment]
@flying-sheep You may want to add a short notice to the crates.io description, e.g.: 

    If you are looking for the requirements tracking tool `rst` (Requirements, Specifications and Tests), have a look at the `rst_app` package instead.

That way nobody gets lost :)

**Comment by flying-sheep** [comment]
will do asap!
